version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on: 
      - app
    ports:
      - "80:80"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

